apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: duckdns-secret
spec:
  encryptedData:
    token: AgDikwDz2b1XDRlqTTVqgrF2nBkhCFubq/odZR7d9VNCRxnke1kt0e4fe6fxdtvHWSpNixXenLWKib5rIALE/1VGF4ncA0N1oqrcUrY5jwwzOvZzCJqcMIHwxDd5DXy7OHU1PzQ5bJko0ds5AxCGyY8HM5pXiXPhqD7VeEzAkhFSu2Te0tbPm/Up7doAnQ/5KkxYLSL4m8cskL4c1T39dWIo+IMPMFf6AxDbmFyehK9fDRW5fArYtvDGLBdIjeh+fuwMhu3tV0P5kUpqLm6//DGArZyg8acxz9X0NjSnzCIodOlbFJnUQujC6GgH6kqPNMMZXo30vfGEiFJwqoOTtE6bdl2PPozx0vXZI8WWhVk8bTnLfJ2x2lQkvkCTQlx+/9Jl40Z+OXQ1zpe4a/Vcjsirp2eM/i6zWxTWxtP1rqKtmi639S6ZXnRZywFOh5tcVeZI/GO2q4p8zz4P7qr4qvcbHj7Iyx6+m8tCGO2hH2mGwkcGzq/PDnxUyt0unERtdhhbuAYobLrPAO85KA4/9Sry3WhZuTzSs8fARlReGGcwaGXL2MJ7DEsxE6bNMk/ruThbxssmezv1XfIcbaRbzzk3Vl2tWAA1mnywfsuOtK0gD6d2mfryl31BXpjNKHxwig37H4vsiJ0ujLTQmWGWYi/iG5KNYddYO+/GObTm4DYw3zWvor5ZjxxKu0I6NM30X2En7eiX5J6140Dj33nlCoBCdQTiEFwH+vRsGAZouhg8MT0Dcf4=
  template:
    metadata:
      creationTimestamp: null
      name: duckdns-secret
