apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ai-stack-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/spibini/spibini-argocd.git
    targetRevision: HEAD
    path: apps/ai/ollama/overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: ai
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true