apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infrastructure
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://github.com/spibini/spibini-argocd.git"
    targetRevision: HEAD
    path: apps/network
  destination:
    server: "https://kubernetes.default.svc"
    namespace: infra
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
