apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infrastructure
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://github.com/spibini/spibini-argocd.git"
    targetRevision: HEAD
    path: apps/network
  destination:
    server: "https://kubernetes.default.svc"
    namespace: infra
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: infrastructure
spec:
  project: default
  sources:
    - repoURL: https://charts.min.io
      chart: minio
      targetRevision: "5.4.0"
      helm:
        valueFiles:
          - $values/apps/infra/minio/values.yaml
    - repoURL: https://github.com/spibini/spibini-argocd.git
      targetRevision: HEAD
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: minio
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true