apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: linkat-prod-data
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://github.com/spibini/spibini-argocd.git"
    targetRevision: HEAD
    path: apps/linkat/data/overlays/prod
  destination:
    server: "https://kubernetes.default.svc"
    namespace: linkat-prod
  syncPolicy:
    automated: null

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: linkat-prod-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://github.com/spibini/spibini-argocd.git"
    targetRevision: HEAD
    path: apps/linkat/app/overlays/prod
  destination:
    server: "https://kubernetes.default.svc"
    namespace: linkat-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
