server {
    listen 80;
    server_name cdn.link-at.store;

    charset utf-8;

    location / {
        root /usr/share/nginx/html;
        autoindex off; 
        try_files $uri $uri/ =404;
        
        expires 30d;
        add_header Cache-Control "public, no-transform";
    }

    client_max_body_size 10M;
}