apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

nameSuffix: -prod

configMapGenerator:
  - name: nginx-config
    behavior: replace
    files:
      - default.conf

patches:
  - target:
      kind: Deployment
      name: nginx-deployment-prod
    patch: |-
      - op: replace
        path: /spec/template/spec/volumes/1/hostPath/path
        value: /home/deploy/images/prod

  - target:
      kind: Service
      name: nginx-service-prod
    patch: |-
      - op: replace
        path: /spec/ports/0/nodePort
        value: 30081
