apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - pv.yml

nameSuffix: -prod

configMapGenerator:
  - name: nginx-config
    behavior: replace
    files:
      - default.conf

patches:
  - target:
      kind: Service
      name: nginx-service
    patch: |-
      - op: replace
        path: /spec/ports/0/nodePort
        value: 30081

patchesJson6902:
  - target:
      kind: PersistentVolumeClaim
      name: nginx-image-pvc
    patch: |-
      - op: replace
        path: /spec/volumeName
        value: nginx-image-pv-prod
