apiVersion: apps/v1
kind: Deployment
metadata:
  name: linkat-dev-server
  namespace: {{ .Release.Namespace }}
  labels:
    app: linkat-dev-server
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: linkat-dev-server
  template:
    metadata:
      labels:
        app: linkat-dev-server
      annotations:
        instrumentation.opentelemetry.io/inject-java: "true"
    spec:
      containers:
        - name: linkat-dev-server
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          envFrom:
            - secretRef:
                name: {{ .Values.secretName }}
          env:
            - name: TZ
              value: Asia/Seoul
            - name: OTEL_SERVICE_NAME
              value: {{ .Values.otel.serviceName }}
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 40
            periodSeconds: 10
            failureThreshold: 5
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 30