apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../app/base
  - ../data/overlays/preview

patches:
  - target:
      kind: Service
      name: nginx-service
    patch: |-
      - op: replace
        path: /spec/type
        value: ClusterIP
