apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

nameSuffix: -preview

patches:
  - target:
      kind: Deployment
      name: duckdns
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/env/3/value
        value: "qcov-preview"

  - target:
      kind: Deployment
      name: duckdns
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/env/4/valueFrom/secretKeyRef/name
        value: "duckdns-secret-preview"
