apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: duckdns-secret
spec:
  encryptedData:
    token: AgCR1w4oW5cfV2YfKp5+azwEydUlDM+dIeESScxOOrso4QERiAJBBBBdHlOwRw0uv4JHjP6D0AfFUbqb9Vi9xiObYw5wRzDNwaueQvot9m1cOrErjZbnX4OYoP3sxWgoOvmODFDUhMPw156tln84k1HNpOcjtk78gmJjyvU1OVmXjgLIyKMHi+a4iwBNNNbO/hxiJq6/tqqCjUgWTmbWPqIZ/bxgLhODbBMplp4Pcs+35Zg2jCVbMwtNiXC4kjQIQgq78uW1CpU9uMLFrSkQyHC7LZnjsNffl8PNqn79jqmZ8zEy08IuS3/s2zs3IPmknljUDWu94UpyaQpeV1Ak1D8uXx8W+gE2otPdhiVD/VmtzzCHm0PeZ+9hQ1hhdI6GiDtJNGlRJZAi37pAAP3kGJ6Rci1O1b+2XakJoUJ6kz3khFHLOHS+OnVAW6jMcwDRmMn80WEoKo5/0pxFC0b1+aV6+EyDkz+PUl4a/AgMsQ8Y1jHjQL9oZvHEivMkMj4hlksoqpOZ4HLoRJXIxjP5qr5JFqU/uNewPxPj11luFBNIy5WGBgGt4tAGuAlcT+joL+3QrHBoopqgxNS6TTWSbVS01vF7AMCF1+dmQO9Fjcssr2pPC4jPUCMdKB9yfZoYIXmSKedhwHVQvmNzxKiCOcPpk3RBWIjElhkpIGzSqRfgjdtUHgTMi6JPKYBQjeG14rkMPDFENsRMehR3LNl5wVGpoqq4XPRo+9KxCaDes3pIwzKkU+g=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: duckdns-secret
