image:
  repository: qcov/linkat
  tag: latest

replicaCount: 1

service:
  type: NodePort
  port: 8080
  nodePort: 30090

secretName: linkat-dev-env

otel:
  enabled: true
  endpoint: "http://otel-collector.monitoring.svc.cluster.local:4317"
  serviceName: "linkat-dev-server"