apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-image-server-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://github.com/spibini/spibini-argocd.git"
    targetRevision: HEAD
    path: apps/nginx-image-server/overlays/dev
  destination:
    server: "https://kubernetes.default.svc"
    namespace: linkat-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
